version: '3.8'

services:
  application:
    image: managemate.application:${VERSION:-latest}
    restart: unless-stopped
    build:
      context: ./Application
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5211
    ports:
      - "5211:5211"
    depends_on:
      - database

  database:
    image: postgres:latest
    restart: unless-stopped
    container_name: managemate.database
    environment:
      POSTGRES_DB: managemate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
