
services:
  managemate.application:
    image: ${DOCKER_REGISTRY:-myregistry/}managemate.application:${VERSION:-latest}
    build:
        context: ./Application
        dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
    ports:
      - "5000:5000"
      - "5001:5001"

  managemate.database:
    image: postgres:latest
    container_name: managemate.database
    environment:
      - POSTGRES_DB=managemate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
     - ./.containers/managemate:/var/lib/postgresql/data
    ports:
     - 5432:5432    