
services:
  application:
    image: managemate.application:${VERSION:-latest}
    build:
        context: ./Application
        dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Debug
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
    ports:
      - "50000:50000"
      - "50001:50001"

  database:
    image: postgres:latest
    container_name: managemate.database
    environment:
      - POSTGRES_DB=managemate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
     - ./.containers/managemate:/var/lib/postgresql/data
    ports:
     - 5432:5432    