services:
  application:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
    ports:
      - "50000:50000"
      - "50001:50001"
    volumes:
      - /Users/benjamin/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - /Users/benjamin/.aspnet/https:/root/.aspnet/https:ro